server:
  ip: 0.0.0.0
  port: 8082
  enableH2C: false
  enableSSL: false
mysql:
  dsn: root:Mysql123456.@tcp(127.0.0.1:3306)/timemanage?charset=utf8mb4&parseTime=true&timeout=30s&readTimeout=30s
  maxIdle: 1
  maxOpenConn: 2
jwt:
  secret: p123456
  redisKey: token_cache
redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password: Redis1234.
  idleTimeout: 300