// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://127.0.0.1",
        "contact": {
            "name": "jewel"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/categories/delete/:id": {
            "post": {
                "description": "删除分类",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分类API"
                ],
                "summary": "删除分类",
                "operationId": "DeleteCategory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "enjmcvhdwernxhcuvyudfdjfhpq",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "分类ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/categories/list": {
            "get": {
                "description": "查询分类列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分类API"
                ],
                "summary": "查询分类列表",
                "operationId": "CategoryGetList",
                "parameters": [
                    {
                        "type": "string",
                        "description": "enjmcvhdwernxhcuvyudfdjfhpq",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "11",
                        "name": "ParentID",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.CategoriesRespose"
                            }
                        }
                    }
                }
            }
        },
        "/categories/save": {
            "post": {
                "description": "创建或修改分类",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分类API"
                ],
                "summary": "创建或修改分类",
                "operationId": "SaveCategory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "enjmcvhdwernxhcuvyudfdjfhpq",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "Json",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SaveCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "int64"
                        }
                    }
                }
            }
        },
        "/common/user/forget/password": {
            "post": {
                "description": "忘记密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "COMMON API"
                ],
                "summary": "忘记密码",
                "operationId": "ForgetPassword",
                "parameters": [
                    {
                        "description": "Json",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1",
                        "schema": {
                            "type": "int"
                        }
                    }
                }
            }
        },
        "/common/user/login": {
            "post": {
                "description": "登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "COMMON API"
                ],
                "summary": "登录",
                "operationId": "Login",
                "parameters": [
                    {
                        "description": "Json",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/common/user/register": {
            "post": {
                "description": "注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "COMMON API"
                ],
                "summary": "注册",
                "operationId": "Register",
                "parameters": [
                    {
                        "description": "Json",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1",
                        "schema": {
                            "type": "int"
                        }
                    }
                }
            }
        },
        "/common/user/send/code": {
            "post": {
                "description": "发送验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "COMMON API"
                ],
                "summary": "发送验证码",
                "operationId": "SendCode",
                "parameters": [
                    {
                        "description": "Json",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SendCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/tasks/delete/:id": {
            "post": {
                "description": "删除任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务API"
                ],
                "summary": "删除任务",
                "operationId": "DeleteTask",
                "parameters": [
                    {
                        "type": "string",
                        "description": "enjmcvhdwernxhcuvyudfdjfhpq",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/tasks/list": {
            "get": {
                "description": "查询任务列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务API"
                ],
                "summary": "查询任务列表",
                "operationId": "TaskGetList",
                "parameters": [
                    {
                        "type": "string",
                        "description": "enjmcvhdwernxhcuvyudfdjfhkjxkjaoerpq",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "10",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.TasksRespose"
                            }
                        }
                    }
                }
            }
        },
        "/tasks/save": {
            "post": {
                "description": "保存或修改任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务API"
                ],
                "summary": "保存或修改任务",
                "operationId": "SaveTask",
                "parameters": [
                    {
                        "type": "string",
                        "description": "enjmcvhdwernxhcuvyudfdjfhpq",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "Json",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SaveTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "int64"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.LoginRequest": {
            "type": "object",
            "required": [
                "name",
                "password"
            ],
            "properties": {
                "name": {
                    "description": "用户名或邮箱",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                }
            }
        },
        "request.RegisterRequest": {
            "type": "object",
            "required": [
                "code",
                "email",
                "name",
                "password"
            ],
            "properties": {
                "code": {
                    "description": "验证码",
                    "type": "string",
                    "example": "888888"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string",
                    "example": "test@mail.com"
                },
                "name": {
                    "description": "用户名",
                    "type": "string"
                },
                "password": {
                    "description": "新密码",
                    "type": "string"
                }
            }
        },
        "request.SaveCategoryRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "id": {
                    "description": "分类ID",
                    "type": "integer"
                },
                "name": {
                    "description": "分类名称",
                    "type": "string"
                },
                "parentID": {
                    "description": "上级分类ID",
                    "type": "integer"
                }
            }
        },
        "request.SaveTaskRequest": {
            "type": "object",
            "required": [
                "categoryID",
                "description",
                "endTime",
                "startTime"
            ],
            "properties": {
                "categoryID": {
                    "description": "任务所属分类ID",
                    "type": "integer"
                },
                "description": {
                    "description": "任务描述",
                    "type": "string"
                },
                "endTime": {
                    "description": "任务结束时间",
                    "type": "integer"
                },
                "id": {
                    "description": "任务ID",
                    "type": "integer"
                },
                "startTime": {
                    "description": "任务开始时间",
                    "type": "integer"
                }
            }
        },
        "request.SendCodeRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string",
                    "example": "test@mail.com"
                }
            }
        },
        "response.CategoriesRespose": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "分类ID",
                    "type": "integer"
                },
                "level": {
                    "description": "分类等级",
                    "type": "integer"
                },
                "name": {
                    "description": "分类名称",
                    "type": "string"
                },
                "parentID": {
                    "description": "上级分类ID",
                    "type": "integer"
                },
                "path": {
                    "description": "分类路径",
                    "type": "string"
                },
                "userID": {
                    "description": "创建该分类的用户ID",
                    "type": "integer"
                }
            }
        },
        "response.TasksRespose": {
            "type": "object",
            "properties": {
                "categories": {
                    "description": "任务所属分类",
                    "type": "string"
                },
                "description": {
                    "description": "任务描述",
                    "type": "string"
                },
                "endTime": {
                    "description": "任务结束时间",
                    "type": "integer"
                },
                "id": {
                    "description": "任务ID",
                    "type": "integer"
                },
                "spentTime": {
                    "description": "花费时间",
                    "type": "integer"
                },
                "startTime": {
                    "description": "任务开始时间",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "time manage",
	Description:      "time manage",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
