basePath: /api/v1
definitions:
  request.LogErrorRequest:
    properties:
      error:
        description: 错误信息
        type: string
      stack:
        description: 堆栈
        type: string
      version:
        description: 版本
        type: string
    type: object
  request.LoginRequest:
    properties:
      name:
        description: 用户名或邮箱
        type: string
      password:
        description: 密码
        type: string
    required:
    - name
    - password
    type: object
  request.RegisterEquipmentRequest:
    properties:
      imei0:
        description: IMEI0
        type: string
      imei1:
        description: IMEI1
        type: string
      isPhysicalDevice:
        description: 是否为物理设备
        type: integer
      os:
        description: 所属操作系统
        type: string
      sn:
        description: 序列号
        type: string
      type:
        description: 设备类型
        type: string
      vender:
        description: 供应商
        type: string
    type: object
  request.RegisterRequest:
    properties:
      code:
        description: 验证码
        example: "888888"
        type: string
      email:
        description: 邮箱
        example: test@mail.com
        type: string
      name:
        description: 用户名
        type: string
      password:
        description: 新密码
        type: string
    required:
    - code
    - email
    - name
    - password
    type: object
  request.SaveCategoryRequest:
    properties:
      id:
        description: 分类ID
        type: integer
      name:
        description: 分类名称
        type: string
      parentID:
        description: 上级分类ID
        type: integer
    required:
    - name
    type: object
  request.SaveTaskRequest:
    properties:
      categoryID:
        description: 任务所属分类ID
        type: integer
      description:
        description: 任务描述
        type: string
      endTime:
        description: 任务结束时间
        type: integer
      id:
        description: 任务ID
        type: integer
      startTime:
        description: 任务开始时间
        type: integer
    required:
    - categoryID
    - endTime
    type: object
  request.SendCodeRequest:
    properties:
      email:
        description: 邮箱
        example: test@mail.com
        type: string
    required:
    - email
    type: object
  response.CategoriesResponse:
    properties:
      id:
        description: 分类ID
        type: integer
      level:
        description: 分类等级
        type: integer
      name:
        description: 分类名称
        type: string
      parentID:
        description: 上级分类ID
        type: integer
      path:
        description: 分类路径
        type: string
      userID:
        description: 创建该分类的用户ID
        type: integer
    type: object
  response.TasksResponse:
    properties:
      categories:
        description: 任务所属分类
        type: string
      categoryID:
        description: 任务所属分类ID
        type: integer
      description:
        description: 任务描述
        type: string
      endTime:
        description: 任务结束时间
        type: integer
      id:
        description: 任务ID
        type: integer
      spentTime:
        description: 花费时间
        type: integer
      startTime:
        description: 任务开始时间
        type: integer
    type: object
host: 127.0.0.1:8081
info:
  contact:
    name: jewel
  description: time manage
  termsOfService: http://127.0.0.1
  title: time manage
  version: "1.0"
paths:
  /categories/delete/:id:
    post:
      consumes:
      - application/json
      description: 删除分类
      operationId: DeleteCategory
      parameters:
      - description: enjmcvhdwernxhcuvyudfdjfhpq
        in: header
        name: token
        type: string
      - description: 分类ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: boolean
      summary: 删除分类
      tags:
      - 分类API
  /categories/list:
    get:
      consumes:
      - application/json
      description: 查询分类列表
      operationId: CategoryGetList
      parameters:
      - description: enjmcvhdwernxhcuvyudfdjfhpq
        in: header
        name: token
        type: string
      - description: "11"
        in: query
        name: parentID
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            items:
              $ref: '#/definitions/response.CategoriesResponse'
            type: array
      summary: 查询分类列表
      tags:
      - 分类API
  /categories/save:
    post:
      consumes:
      - application/json
      description: 创建或修改分类
      operationId: SaveCategory
      parameters:
      - description: enjmcvhdwernxhcuvyudfdjfhpq
        in: header
        name: token
        type: string
      - description: Json
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/request.SaveCategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: int64
      summary: 创建或修改分类
      tags:
      - 分类API
  /common/system/log/error:
    post:
      consumes:
      - application/json
      description: 记录前端日志错误
      operationId: LogError
      parameters:
      - description: Json
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/request.LogErrorRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: integer
      summary: 记录前端日志错误
      tags:
      - COMMON API
  /common/system/register/equipment:
    post:
      consumes:
      - application/json
      description: 注册设备
      operationId: RegisterEquipment
      parameters:
      - description: Json
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/request.RegisterEquipmentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: integer
      summary: 注册设备
      tags:
      - COMMON API
  /common/user/forget/password:
    post:
      consumes:
      - application/json
      description: 忘记密码
      operationId: ForgetPassword
      parameters:
      - description: Json
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/request.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: "1"
          schema:
            type: int
      summary: 忘记密码
      tags:
      - COMMON API
  /common/user/login:
    post:
      consumes:
      - application/json
      description: 登录
      operationId: Login
      parameters:
      - description: "3425243"
        in: header
        name: equipment
        type: string
      - description: Json
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            type: string
      summary: 登录
      tags:
      - COMMON API
  /common/user/register:
    post:
      consumes:
      - application/json
      description: 注册
      operationId: Register
      parameters:
      - description: Json
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/request.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: "1"
          schema:
            type: int
      summary: 注册
      tags:
      - COMMON API
  /common/user/send/code:
    post:
      consumes:
      - application/json
      description: 发送验证码
      operationId: SendCode
      parameters:
      - description: Json
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/request.SendCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: boolean
      summary: 发送验证码
      tags:
      - COMMON API
  /tasks/delete/:id:
    post:
      consumes:
      - application/json
      description: 删除任务
      operationId: DeleteTask
      parameters:
      - description: enjmcvhdwernxhcuvyudfdjfhpq
        in: header
        name: token
        type: string
      - description: 任务ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: boolean
      summary: 删除任务
      tags:
      - 任务API
  /tasks/last/time:
    get:
      consumes:
      - application/json
      description: 获取最后一个结束时间
      operationId: GetLastEndTime
      parameters:
      - description: enjmcvhdwernxhcuvyudfdjfhkjxkjaoerpq
        in: header
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: integer
      summary: 获取最后一个结束时间
      tags:
      - 任务API
  /tasks/list:
    get:
      consumes:
      - application/json
      description: 查询任务列表
      operationId: TaskGetList
      parameters:
      - description: enjmcvhdwernxhcuvyudfdjfhkjxkjaoerpq
        in: header
        name: token
        type: string
      - description: "1"
        in: query
        name: page
        type: integer
      - description: "10"
        in: query
        name: size
        type: integer
      - description: 开始时间
        in: query
        name: startTime
        required: true
        type: integer
      - description: 结束时间
        in: query
        name: endTime
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            items:
              $ref: '#/definitions/response.TasksResponse'
            type: array
      summary: 查询任务列表
      tags:
      - 任务API
  /tasks/save:
    post:
      consumes:
      - application/json
      description: 保存或修改任务
      operationId: SaveTask
      parameters:
      - description: enjmcvhdwernxhcuvyudfdjfhpq
        in: header
        name: token
        type: string
      - description: Json
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/request.SaveTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: int64
      summary: 保存或修改任务
      tags:
      - 任务API
swagger: "2.0"
